# Base blog settings
baseurl                      : "" # the subpath of your site,                         # e.g. /blog/
                              # set to '' in case of hosting on GitHub
url                          : "" # the base hostname & protocol for your site
                                  # `http://<username>.github.io` - for GitHub

blog:
  title                      : donghunholic
  description                  : >
                               this should contain a proper description

# Layout configuration
  logo_path                  : #"assets/img/dactl.svg" # path to logo file
  search_path                : # "yourgitusername.github.io"
                               # needed for searchbox in archive page
  hero_layout                : true # turn on hero layout for blog and posts
  hero_placeholder           : "assets/img/generic_hero.jpg" # placeholder for hero image
  excerpts                   : true # show excerpts instead of full post content on blog page
  inline_footnotes           : true # enable/disable barefoot inline footnotes
  titles_only                : false # show post titles only on main blog page

# Fonts
  font                       : '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts          : 'Rubik:400,400italic,700,700italic'


# Author info
author:
  fullname                  : Donghun Shin
#  rss                       : true # generate RSS feed and show it's icon in header
  mail                      : sdh728@postech.ac.kr
#  twitter                   : twitter-user-name
  github                    : donghunholic
#  youtube                   : youtube-user-name
#  stackoverflow             : stackoverflow-user-name
#  disqus                    : dactl # your disqus site name
#  google_analytics          : # 'UA-XXXXXXXX-X'
#  photo                     : "uploads/me2.png"
#  photo2x                   : "uploads/me.png"



## !!
## Advanced blog settings
## You should not change anything here unless you know what you are doing

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Permalinks
permalink                    : posts/:slug

# Posts
excerpt_separator            : <!–-break-–>

# Pagination
paginate                     : 5
paginate_path                : '/page-:num/'

# Tags
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog-by-tag

# Handling Reading
exclude                    : ["README.md", "README.html"]

# https://github.com/jekyll/jekyll/issues/4619
# Markdown and highlighter settings
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge
lsi: false
excerpt_separator: false
incremental: false

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
# kramdown:
#   input:          GFM
#   # https://github.com/jekyll/jekyll/pull/4090
#   math_engine: mathjax
#   syntax_highlighter: rouge

#   # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
#   # span, block element options fall back to global
#   syntax_highlighter_opts:
#     # Rouge Options › https://github.com/jneen/rouge#full-options
#     # css_class: 'highlight'
#     #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1

kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  entity_output: as_char
  toc_levels: 1..6
  footnote_nr: 1
  show_warnings: false
  syntax_highlighter: rouge
  math_engine: mathjax
  parse_span_html: true
  remove_span_html_tags: false
  transliterated_header_ids: false
  auto_ids: true
  enable_coderay: false
  ignore_errors: false
  parse_block_html: true
  parse_span_html: true
  template: GFM

# Sass settings
sass:
  sass_dir                : _sass
  style                   : compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings               : all
  endings                 : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false
  ignore:
  envs                    : [local]

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
